[tool.poetry]
name = "consensus-sigs"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.11"
sigprofilerassignment = "^0.2.3"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
